version: '3.7'
services:
  starter:
    container_name: threadsafe
    image: ddivad195/threadsafe:latest
    volumes:
      - type: bind
        source: ./config/config.json
        target: /config/config.json
    restart: always
    env_file:
      - .env

volumes:
  app: